# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadrotor_msgs/QuadData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class QuadData(genpy.Message):
  _md5sum = "3365da27984a42534fc450cae3096cf6"
  _type = "quadrotor_msgs/QuadData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
float64 z
float64 vx
float64 vy
float64 vz
float64 acc_x
float64 acc_y
float64 acc_z
float64 yaw
int8 mode
int8 write"""
  __slots__ = ['x','y','z','vx','vy','vz','acc_x','acc_y','acc_z','yaw','mode','write']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64','int8','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,vx,vy,vz,acc_x,acc_y,acc_z,yaw,mode,write

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(QuadData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.vx is None:
        self.vx = 0.
      if self.vy is None:
        self.vy = 0.
      if self.vz is None:
        self.vz = 0.
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.yaw is None:
        self.yaw = 0.
      if self.mode is None:
        self.mode = 0
      if self.write is None:
        self.write = 0
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.vx = 0.
      self.vy = 0.
      self.vz = 0.
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.yaw = 0.
      self.mode = 0
      self.write = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_10d2b.pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.acc_x, _x.acc_y, _x.acc_z, _x.yaw, _x.mode, _x.write))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 82
      (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.acc_x, _x.acc_y, _x.acc_z, _x.yaw, _x.mode, _x.write,) = _struct_10d2b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_10d2b.pack(_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.acc_x, _x.acc_y, _x.acc_z, _x.yaw, _x.mode, _x.write))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 82
      (_x.x, _x.y, _x.z, _x.vx, _x.vy, _x.vz, _x.acc_x, _x.acc_y, _x.acc_z, _x.yaw, _x.mode, _x.write,) = _struct_10d2b.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_10d2b = struct.Struct("<10d2b")
